name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run simple smoke test
      run: |
        python - <<'PY'
import sys
try:
    import flask
    print('Flask OK')
except Exception as e:
    print('Erro:', e)
    sys.exit(1)
PY
