name: Flask App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flask

      - name: Verificar estrutura do projeto
        run: |
          echo "Arquivos e pastas do projeto:"
          ls -R

      - name: Testar inicialização do Flask
        run: |
          echo "Testando se o app Flask inicia..."
          python -c "import app; print('✅ Flask importado e pronto!')"
